# This is a basic workflow to help you get started with Actions

name: Overdose scraper

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 14 * * *" #2pm daily. https://crontab.guru/examples.html

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# required for python/github bug. may not be req'd
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        # github sets this for you
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Install needed libs
      - name: Install dependencies
        run: |
          python -m pip install TableauScraper
          python -m pip install pandas

      # Runs our python script
      - name: Run scraper
        run: python init.py

      # Commits files
      - name: Commit results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # github sets this for you
        # uses: mikeal/publish-to-github-action@master
        run: |
          git config --global user.email "action@hgithub.com"
          git config --global user.name "Github action"
          git add -A
          git commit -am "ran data update script"
          git push
